sudo: required

language: node_js

branches:
  except:
  - gh-pages

services:
  - docker

node_js:
  - 8

install:
  - echo "Running install"

before_script:
  - echo "Running before script"

script:
  - echo "Running script"
  - cd api && make deps && make test
