matrix:
  include:
    - name: "oma-opintopolku-loki frontend API"
      language: node_js
      node_js: 8
      cache: npm
      before_script:
        - cd api
      script:
        - make deps && make test

    - name: "oma-opintopolku-loki frontend"
      language: node_js
      node_js: 8
      cache: npm
      sudo: required
      services:
        - docker
        - xvfb
      env:
        - TEST_PORT=3030
      before_install:
        - "sysctl kernel.unprivileged_userns_clone=1"
        - export TZ=Europe/Helsinki
      before_script:
        - cd frontend
      script:
        - npm install && npm run test
        - npm run unit
        - npm run lint

    - name: "oma-opintopolku-loki log parser"
      language: java
      jdk: openjdk8
      sudo: required
      services:
        - docker

      cache:
        directories:
          - $HOME/.m2
      before_script:
        - cd parser
      script:
        - make test
        - make scalastyle
