service: api

provider:
  name: aws
  runtime: nodejs8.10

iamRoleStatements:
  - Effect: Allow
  Action:
    - dynamodb:Scan

functions:
  auditlog:
    handler: auditlog/src/handler.auditlog
    events:
      - https:
        method: get
        path: auditlogs/{oid}
        authrozier: aws_iam
        request:
          parameters:
            paths:
              oid: true

