service: api

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: PRODUCTION
    NODE_CONFIG_ENV: ${opt:stage, 'dev'}

package:
  exclude:
    - .idea/**
  include:
    - config

plugins:
  localPath: './auditlog/node_modules'
  modules:
    - serverless-domain-manager

functions:
  auditlog:
    description: Function for reading audit log entries from DynamoDB and returning them
    role: ${ssm:/oma-opintopolku-loki/auditlog-api/role/arn}
    memorySize: 256
    timeout: 30
    handler: auditlog/src/entrypoint.handler
    events:
      - http:
          path: auditlog
          method: get
          cors: true

  whoami:
    description: Return used oid, firstname and lastname, as returned by Shibboleth
    role: ${ssm:/oma-opintopolku-api/whoami/role/arn}
    memorySize: 128
    timeout: 10
    handler: whoami/src/entrypoint.handler
    events:
      - http:
          path: whoami
          method: get
          cors: true

custom:
  domains:
    dev:  oma-opintopolku-loki-dev.testiopintopolku.fi
    qa:   oma-opintopolku-loki-qa.testiopintopolku.fi
    prod: oma-opintopolku-loki.opintopolku.fi
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    stage: ${opt:stage, 'dev'}
    createRoute53Record: true
    endpointType: 'edge'
