service: api

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: ${opt:stage, 'dev'}

functions:
  auditlog:
    description: Function for reading audit log entries from DynamoDB and returning them
    role: ${ssm:/oma-opintopolku-loki/auditlog-api/role/arn}
    memorySize: 256
    timeout: 60
    handler: auditlog/src/entrypoint.handler
    events:
      - http:
          path: auditlog/{oid}
          method: get
          cors: true
