name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (dev/qa/prod)"
        required: true
        default: "dev"
      commithash:
        description: "Commit hash to deploy from"

jobs:
  deploy_parser:
    name: Deploy Parser
    environment:
      name: ${{ github.event.inputs.environment }}
    env:
      ENV_NAME: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commithash }}

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          architecture: 'x64'
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v4
        if: steps.check-image.image-exists != '0'
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Assume role for target environment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
          role-duration-seconds: 3600
          role-session-name: LokiDeployment-${{ github.event.inputs.commithash }}

      - name: Deploy parser
        run: |
          cd parser
          make deploy env=$ENV_NAME

  deploy_frontend:
    name: Deploy Frontend
    environment:
      name: ${{ github.event.inputs.environment }}
    env:
      ENV_NAME: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commithash }}

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Assume role for target environment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
          role-duration-seconds: 3600
          role-session-name: LokiDeployment-${{ github.event.inputs.commithash }}

      - name: Deploy frontend
        run: |
          cd frontend
          ./deploy.sh $ENV_NAME
