name: Run tests
on:
  push:
    branches-ignore:
      - "master"
  workflow_dispatch:
env:
  DOCKER_BUILDKIT: 1
jobs:
  oma_opintopolku_loki_frontend:
    name: oma-opintopolku-loki frontend
    runs-on: ubuntu-20.04
    env:
      TEST_PORT: 3030
      TZ: Europe/Helsinki
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run tests
        run: |
          cd frontend
          npm install && npm run test
          npm run unit
          npm run lint

  oma_opintopolku_loki_parser:
    name: oma-opintopolku-loki log parser
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          architecture: 'x64'
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: |
          cd parser
          mvn -version
          make test
          make scalastyle
